"""add water_logs and step_logs tables

Revision ID: 70767db6f690
Revises: e69b4d892209
Create Date: 2025-09-05 14:32:47.334812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70767db6f690'
down_revision: Union[str, Sequence[str], None] = 'e69b4d892209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "water_logs",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("date", sa.Date, nullable=False, server_default=sa.text("CURRENT_DATE")),
        sa.Column("amount", sa.Integer, nullable=False, server_default="0"),
    )
    op.create_index("ix_water_logs_user_date", "water_logs", ["user_id", "date"], unique=True)

    op.create_table(
        "step_logs",
        sa.Column("id", sa.Integer, primary_key=True, index=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id")),
        sa.Column("date", sa.Date, nullable=False, server_default=sa.text("CURRENT_DATE")),
        sa.Column("steps", sa.Integer, nullable=False, server_default="0"),
    )
    op.create_index("ix_step_logs_user_date", "step_logs", ["user_id", "date"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_step_logs_user_date", table_name="step_logs")
    op.drop_table("step_logs")

    op.drop_index("ix_water_logs_user_date", table_name="water_logs")
    op.drop_table("water_logs")
    # ### end Alembic commands ###
