"""add_health_plan_fields

Revision ID: a340e1c652ef
Revises: 70767db6f690
Create Date: 2026-07-12 17:13:28.107912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a340e1c652ef'
down_revision: Union[str, Sequence[str], None] = '70767db6f690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('workout_plan', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('avoidance_list', sa.JSON(), nullable=True))
    op.add_column('plans', sa.Column('budget_tips', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'budget_tips')
    op.drop_column('plans', 'avoidance_list')
    op.drop_column('plans', 'workout_plan')
    # ### end Alembic commands ###
