import json
import uuid
from fastapi import APIRouter, Depends, Request, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from db.session import get_db, SessionLocal
from services.meal_plan_ai import generate_meal_plan
from services.health_plan_ai import generate_complete_health_plan
from db.models.food import FoodItem
from db.models.plan import Plan, PlanItem
from schemas.plan import GeneratedPlanSchema
from utils import get_day_name

router = APIRouter(
    prefix="/v1/generate-plan",
    tags=["Generate AI Plan"]
)

TASKS = {}

def _generate_plan_task(task_id: str, user_id: int, days: int, user_profile: dict):
    db = SessionLocal()
    try:
        TASKS[task_id] = {"status": "processing"}
        
        foods = db.query(FoodItem).all()
        food_list = [
            {
                "id": f.id,
                "name": f.name,
                "calories": float(f.calories),
                "protein": float(f.protein),
                "carbs": float(f.carbs),
                "fats": float(f.fats),
                "reference_amount": float(f.reference_amount),
                "reference_unit": f.reference_unit
            }
            for f in foods
        ]

        raw_plan = generate_meal_plan(user_profile, food_list, days)

        if isinstance(raw_plan, GeneratedPlanSchema):
            plan_data = raw_plan
        else:
            plan_data = GeneratedPlanSchema.model_validate(raw_plan)
            
        day_name = get_day_name(days)
        existing_plan = (
            db.query(Plan)
            .filter(
                Plan.user_id == user_id,
                Plan.name == f"{day_name} AI Meal Plan"
            )
            .first()
        )

        if existing_plan:
            db.query(PlanItem).filter(PlanItem.plan_id == existing_plan.id).delete()
            existing_plan.description = "Updated by AI"
            plan_record = existing_plan
        else:
            plan_record = Plan(
                user_id=user_id,
                name=f"{day_name} AI Meal Plan",
                description="Generated by AI"
            )
            db.add(plan_record)
            db.commit()
            db.refresh(plan_record)

        for meal in plan_data.meals:
            for item in meal.items:
                db.add(PlanItem(
                    plan_id=plan_record.id,
                    food_id=item.food_id,
                    quantity=item.quantity,
                    unit=item.unit,
                    meal_name=meal.meal,
                    day=plan_data.day
                ))
        db.commit()

        plan_dict = plan_data.model_dump()
        plan_dict = json.loads(json.dumps(plan_dict, default=float))

        TASKS[task_id] = {
            "status": "completed",
            "plan_id": plan_record.id,
            "plan": plan_dict
        }

    except Exception as e:
        TASKS[task_id] = {"status": "failed", "error": str(e)}
    finally:
        db.close()

@router.post("/")
def auto_generate_plan(request: Request, background_tasks: BackgroundTasks, days: int = 1):
    current_user = request.state.user
    
    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi
    }
    
    task_id = str(uuid.uuid4())
    TASKS[task_id] = {"status": "pending"}
    
    background_tasks.add_task(_generate_plan_task, task_id, current_user.id, days, user_profile)
    
    return {
        "message": "AI meal plan generation started",
        "task_id": task_id
    }

@router.get("/status/{task_id}")
def get_task_status(task_id: str):
    task = TASKS.get(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return task

@router.post("/complete")
async def auto_generate_complete_plan(request: Request, day: int | None = None, days: int | None = None, db: Session = Depends(get_db)):
    target_day = day if day is not None else (days if days is not None else 1)
    current_user = request.state.user

    foods = db.query(FoodItem).all()
    food_list = [
        {
            "id": f.id,
            "name": f.name,
            "calories": float(f.calories),
            "protein": float(f.protein),
            "carbs": float(f.carbs),
            "fats": float(f.fats),
            "reference_amount": float(f.reference_amount),
            "reference_unit": f.reference_unit
        }
        for f in foods
    ]

    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi,
        "allergies": current_user.allergies,
        "budget": current_user.budget
    }

    try:
        plan = await generate_complete_health_plan(user_profile, food_list, target_day)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Graph execution failed: {e}")

    plan_dict = plan.model_dump()
    plan_dict = json.loads(json.dumps(plan_dict, default=float))

    # Store complete plan in database
    day_name = get_day_name(target_day)
    existing_plan = (
        db.query(Plan)
        .filter(
            Plan.user_id == current_user.id,
            Plan.name == f"{day_name} AI Health Plan"
        )
        .first()
    )

    if existing_plan:
        db.query(PlanItem).filter(PlanItem.plan_id == existing_plan.id).delete()
        existing_plan.description = "Complete Health Plan Updated by AI"
        existing_plan.workout_plan = plan_dict.get("workout_plan")
        existing_plan.avoidance_list = plan_dict.get("avoidance_list")
        existing_plan.budget_tips = plan_dict.get("budget_tips")
        plan_record = existing_plan
    else:
        plan_record = Plan(
            user_id=current_user.id,
            name=f"{day_name} AI Health Plan",
            description="Complete Health Plan Generated by AI",
            workout_plan=plan_dict.get("workout_plan"),
            avoidance_list=plan_dict.get("avoidance_list"),
            budget_tips=plan_dict.get("budget_tips")
        )
        db.add(plan_record)
        db.commit()
        db.refresh(plan_record)

    for meal in plan.meal_plan:
        for item in meal.items:
            db.add(PlanItem(
                plan_id=plan_record.id,
                food_id=item.food_id,
                quantity=item.quantity,
                unit=item.unit,
                meal_name=meal.meal,
                day=plan.day
            ))
    db.commit()

    return {
        "message": "Complete health plan generated successfully via LangGraph Agents",
        "plan_id": plan_record.id,
        "plan": plan_dict
    }

