import json
from fastapi import APIRouter, Depends, Request, HTTPException
from sqlalchemy.orm import Session
from db.session import get_db
from services.meal_plan_ai import generate_meal_plan
from db.models.food import FoodItem
from db.models.plan import Plan, PlanItem, AIPlan
from schemas.plan import GeneratedPlanSchema

router = APIRouter(
    prefix="/v1/generate-plan",
    tags=["Generate AI Plan"]
)

@router.post("/")
def auto_generate_plan(request: Request, days: int = 1, db: Session = Depends(get_db)):
    current_user = request.state.user

    foods = db.query(FoodItem).all()
    food_list = [
        {
            "id": f.id,
            "name": f.name,
            "calories": float(f.calories),
            "protein": float(f.protein),
            "carbs": float(f.carbs),
            "fats": float(f.fats),
            "reference_amount": float(f.reference_amount),
            "reference_unit": f.reference_unit
        }
        for f in foods
    ]

    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi
    }

    raw_plan = generate_meal_plan(user_profile, food_list, days)

    # Normalize to Pydantic schema (accept dict or GeneratedPlanSchema)
    if isinstance(raw_plan, GeneratedPlanSchema):
        plan_data = raw_plan
    else:
        try:
            plan_data = GeneratedPlanSchema.model_validate(raw_plan)
        except Exception as e:
            raise HTTPException(status_code=422, detail=f"AI response not in expected format: {e}")

    new_plan = Plan(
        user_id=current_user.id,
        name=f"{days}-Day AI Meal Plan",
        description="Generated by AI"
    )
    db.add(new_plan)
    db.commit()
    db.refresh(new_plan)

    for day in plan_data.days:
        for meal in day.meals:
            for item in meal.items:
                db.add(PlanItem(
                    plan_id=new_plan.id,
                    food_id=item.food_id,
                    quantity=item.quantity, 
                    unit=item.unit,
                    meal_name=meal.meal
                ))
    db.commit()

    plan_dict = plan_data.model_dump()
    plan_dict = json.loads(json.dumps(plan_dict, default=float))

    db.add(AIPlan(
        user_id=current_user.id,
        plan_type="meal",
        prompt=None,
        response=plan_dict
    ))
    db.commit()

    return {
        "message": "AI meal plan generated successfully",
        "plan_id": new_plan.id,
        "plan": plan_dict
    }

